[project]
name = "j-reit-report"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "furo>=2024.8.6",
    "linkify-it-py>=2.0.3",
    "myst-parser>=4.0.1",
    "pytest-playwright>=0.7.0",
    "sphinx>=8.2.3",
]
